unset CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
echo "CUDA_MPS_ACTIVE_THREAD_PERCENTAGE="
echo $CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
python rnninfer.py

export CUDA_MPS_ACTIVE_THREAD_PERCENTAGE=31 
echo "CUDA_MPS_ACTIVE_THREAD_PERCENTAGE="
echo $CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
python rnninfer.py

export CUDA_MPS_ACTIVE_THREAD_PERCENTAGE=16
echo "CUDA_MPS_ACTIVE_THREAD_PERCENTAGE="
echo $CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
python rnninfer.py

export CUDA_MPS_ACTIVE_THREAD_PERCENTAGE=6
echo "CUDA_MPS_ACTIVE_THREAD_PERCENTAGE="
echo $CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
python rnninfer.py
